GET http://localhost:5189/games

###

GET http://localhost:5189/games/2

###
POST http://localhost:5189/games
Content-Type: application/json

{
    "name":"Minecraft",
    "genreId": 5,
    "price":19.99,
    "releaseDate":"2011-11-18"
}

###

PUT http://localhost:5189/games/2
Content-Type: application/json

{
    "name":"Street Figting II Turbo",
    "genreId":1,
    "price":29.99,
    "releaseDate":"1991-02-01"
}


###
DELETE  http://localhost:5189/games/2
